# Generated by Django 4.2 on 2024-12-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoJaliApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakDown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('license', models.FileField(upload_to='licenses/')),
                ('insurance', models.FileField(upload_to='insurance/')),
                ('vehicle_number', models.CharField(max_length=50)),
                ('vehicle_registration', models.CharField(max_length=50)),
                ('vehicle_images', models.ImageField(upload_to='vehicle_images/')),
            ],
        ),
    ]
