# Generated by Django 4.2 on 2024-12-03 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoJaliApp', '0002_breakdown'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BreakDown',
            new_name='BreakDownDetails',
        ),
    ]
