# Generated by Django 4.2 on 2024-12-03 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AutoJaliApp', '0003_rename_breakdown_breakdowndetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdowndetails',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
