# Generated by Django 4.2 on 2024-12-03 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AutoJaliApp', '0004_breakdowndetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakdowndetails',
            name='vehicle_images',
        ),
        migrations.AddField(
            model_name='breakdowndetails',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_images/')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_images', to='AutoJaliApp.breakdowndetails')),
            ],
        ),
    ]
