# Generated by Django 4.2 on 2024-12-04 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AutoJaliApp', '0005_remove_breakdowndetails_vehicle_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carowners',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
