# Generated by Django 4.2 on 2024-12-04 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoJaliApp', '0013_carowners_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakdowndetails',
            name='user',
        ),
    ]
