# Generated by Django 4.2 on 2024-12-04 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoJaliApp', '0014_remove_breakdowndetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carowners',
            name='user',
        ),
    ]
