# Generated by Django 4.2 on 2024-12-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoJaliApp', '0018_remove_carowners_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakdowndetails',
            name='is_available',
        ),
        migrations.AddField(
            model_name='breakdowndetails',
            name='vehicle_image',
            field=models.ImageField(default='vehicle_images/placeholder.png', upload_to='vehicle_images/'),
        ),
        migrations.DeleteModel(
            name='VehicleImage',
        ),
    ]
