# Generated by Django 4.2 on 2024-12-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoJaliApp', '0019_remove_breakdowndetails_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdowndetails',
            name='vehicle_model',
            field=models.CharField(default='Unknown Model', max_length=50),
        ),
    ]
