# Generated by Django 4.2 on 2024-12-06 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AutoJaliApp', '0020_breakdowndetails_vehicle_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=255)),
                ('drop_off_location', models.CharField(max_length=255)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoJaliApp.breakdowndetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoJaliApp.carowners')),
            ],
        ),
    ]
