# Generated by Django 4.2 on 2024-12-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoJaliApp', '0021_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='fullname',
            field=models.CharField(default='Unknown order', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='Unknown phone', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.CharField(max_length=100),
        ),
    ]
