# Generated by Django 4.2 on 2024-12-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoJaliApp', '0022_remove_order_user_order_fullname_order_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fare',
            field=models.CharField(default='Unknown fare', max_length=255),
        ),
    ]
